"""Generate public compatibility artifacts from recorded passing evidence."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import tomllib

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "data" / "ecosystem.toml"
GOLDEN = ROOT / "evidence" / "golden-app-compatibility.json"


def _load() -> dict[str, Any]:
    manifest = tomllib.loads(MANIFEST.read_text(encoding="utf-8"))
    golden = json.loads(GOLDEN.read_text(encoding="utf-8"))
    if manifest["schema_version"] != 1 or golden["schema_version"] != 1:
        raise ValueError("unsupported evidence schema")

    golden_versions = {row["package"]: row["version"] for row in golden["packages"]}
    generated_name, generated_version = golden["generated_by"].rsplit(" ", 1)
    golden_versions[generated_name] = generated_version

    packages = manifest["packages"]
    for package in packages:
        if (
            package["golden"]
            and golden_versions.get(package["name"]) != package["version"]
        ):
            raise ValueError(
                f"{package['name']} release {package['version']} does not match "
                f"golden evidence {golden_versions.get(package['name'])}"
            )

    sources = manifest["sources"]
    return {
        "schema_version": 1,
        "as_of": manifest["as_of"],
        "protocols": {
            "mcp": manifest["mcp_revision"],
            "openapi": manifest["openapi_revision"],
        },
        "minimum_python": manifest["minimum_python"],
        "sources": sources,
        "packages": packages,
        "runtimes": manifest["runtimes"],
        "golden_runtime": {
            "python": golden["python"],
            "node": golden["node"],
            "lock_sha256": golden["lock_sha256"],
            "workers": golden["workers"],
            "platform_packages": [
                {
                    "package": row["package"],
                    "version": row["version"],
                }
                for row in golden["packages"]
                if row["package"] in {"workers-py", "workers-runtime-sdk"}
            ],
        },
    }


def _evidence_links(keys: list[str], sources: dict[str, dict[str, str]]) -> str:
    return ", ".join(
        f"[{sources[key]['label']}]({sources[key]['url']})" for key in keys
    )


def _source_line(source: dict[str, str]) -> str:
    line = f"- [{source['label']}]({source['url']}) at `{source['commit']}`"
    if artifact_sha256 := source.get("artifact_sha256"):
        line += f"; aggregate evidence SHA-256 `{artifact_sha256}`"
    return line


def _markdown(data: dict[str, Any]) -> str:
    sources = data["sources"]
    package_rows = "\n".join(
        "| "
        f"[`{package['name']}`](https://github.com/hayatepy/{package['name']}) | "
        f"`{package['version']}` | {package['role']} | "
        f"{'yes' if package['golden'] else 'downstream gate'} | "
        f"{_evidence_links(package['evidence'], sources)} |"
        for package in data["packages"]
    )
    runtime_rows = "\n".join(
        f"| {runtime['name']} | {runtime['contract']} | {runtime['status']} | "
        f"{_evidence_links(runtime['evidence'], sources)} |"
        for runtime in data["runtimes"]
    )
    platform_rows = "\n".join(
        f"| `{package['package']}` | `{package['version']}` |"
        for package in data["golden_runtime"]["platform_packages"]
    )
    workers = data["golden_runtime"]["workers"]
    flags = ", ".join(f"`{flag}`" for flag in workers["flags"])
    source_rows = "\n".join(_source_line(source) for source in sources.values())
    return f"""# Tested ecosystem compatibility

This file is generated by `scripts/export_compatibility.py` from recorded,
passing CI evidence. Do not edit it manually. The evidence snapshot is dated
**{data["as_of"]}**; all packages remain pre-1.0.

## Published package snapshot

| Package | Version | Role | Production golden app | Evidence |
|---|---:|---|---|---|
{package_rows}

## Runtime contracts

| Runtime | Executed or supported contract | Status | Evidence |
|---|---|---|---|
{runtime_rows}

ASGI is a deployment adapter, not a Cloudflare requirement. The Workers class
entrypoint is the feature-complete default. The global entrypoint is HTTP-only
and does not imply named RPC or scheduled class-handler support.

## Golden runtime lock

| Boundary | Tested value |
|---|---|
| Minimum package Python | `{data["minimum_python"]}+` |
| Golden app Python | `{data["golden_runtime"]["python"]}` |
| Golden app Node.js | `{data["golden_runtime"]["node"]}` |
| MCP revision | `{data["protocols"]["mcp"]}` |
| OpenAPI revision | `{data["protocols"]["openapi"]}` |
| Workers compatibility date | `{workers["compatibility_date"]}` |
| Workers flags | {flags} |
| Default Workers entrypoint | {workers["default_entrypoint"]} |
| Optional global entrypoint | {workers["global_entrypoint"]} |

| Platform package | Locked version |
|---|---:|
{platform_rows}

Golden lock SHA-256: `{data["golden_runtime"]["lock_sha256"]}`

## Evidence sources

{source_rows}

Machine-readable data: [`compatibility.json`](../compatibility.json).
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = _load()
    outputs = {
        ROOT / "compatibility.json": json.dumps(data, indent=2, sort_keys=True) + "\n",
        ROOT / "docs" / "COMPATIBILITY.md": _markdown(data),
    }
    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, expected in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            parser.error(
                f"generated compatibility artifacts are stale: {', '.join(stale)}"
            )
        return 0
    for path, expected in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
